stages:
  - build
  - deploy

image: alpine

build_and_push_prod:
  stage: build
  script:
    - echo "This job builds something."

deploy_prod:
  stage: deploy
  needs: [build_and_push_prod]
  script:
    - echo "This job deploys something."