stages:
  - build
  - deploy

image: alpine

build_and_push_dev:
  stage: build
  script:
    - echo "This job builds something."

deploy_dev:
  stage: deploy
  needs: [build_and_push_dev]
  script:
    - echo "This job deploys something."