stages:
  - build
  - deploy

image: alpine

build_and_push_preprod:
  stage: build
  script:
    - echo "This job builds something."

deploy_preprod:
  stage: deploy
  needs: [build_and_push_preprod]
  script:
    - echo "This job deploys something."